// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TrailerOrder.Data;

namespace TrailerOrder.Migrations
{
    [DbContext(typeof(TrailerOrderDbContext))]
    [Migration("20180519014816_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderNumber");

                    b.Property<string>("OrderStatus");

                    b.Property<int?>("TrailerForLoadTrailerID");

                    b.HasKey("OrderID");

                    b.HasIndex("TrailerForLoadTrailerID")
                        .IsUnique()
                        .HasFilter("[TrailerForLoadTrailerID] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TrailerOrder.Models.Trailer", b =>
                {
                    b.Property<int>("TrailerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SerialNumber");

                    b.Property<string>("TrailerNumber");

                    b.Property<string>("TrailerStatus");

                    b.HasKey("TrailerID");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.HasOne("TrailerOrder.Models.Trailer", "TrailerForLoad")
                        .WithOne("orderforTrailer")
                        .HasForeignKey("TrailerOrder.Models.Order", "TrailerForLoadTrailerID");
                });
#pragma warning restore 612, 618
        }
    }
}
