// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TrailerOrder.Data;
using TrailerOrder.Models;

namespace TrailerOrder.Migrations
{
    [DbContext(typeof(TrailerOrderDbContext))]
    partial class TrailerOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrailerOrder.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmployeeID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<DateTime>("TimeIn");

                    b.Property<DateTime>("TimeOut");

                    b.Property<DateTime>("WorkDay");

                    b.HasKey("AttendanceID");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TrailerOrder.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("CustomerName");

                    b.Property<string>("State");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("ZipCode");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TrailerOrder.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AttendanceID");

                    b.Property<string>("City");

                    b.Property<DateTime>("Dob");

                    b.Property<bool>("DotCompliant");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LicExpire");

                    b.Property<DateTime>("LicIssue");

                    b.Property<string>("LicNumber");

                    b.Property<bool>("LoginStatus");

                    b.Property<string>("MedCardNumber");

                    b.Property<DateTime>("MedExpire");

                    b.Property<DateTime>("MedIssue");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordConf");

                    b.Property<string>("SSN");

                    b.Property<string>("SsnConfirm");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<int>("Title");

                    b.Property<string>("UserName");

                    b.Property<string>("WorkStatus");

                    b.Property<string>("ZipCode");

                    b.HasKey("EmployeeID");

                    b.HasIndex("AttendanceID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<int>("CustomerOrdersID");

                    b.Property<DateTime>("DateAssigned");

                    b.Property<DateTime>("DateDelivered");

                    b.Property<DateTime>("DueDate");

                    b.Property<int?>("EmployeeID");

                    b.Property<string>("OrderNumber");

                    b.Property<string>("OrderStatus");

                    b.Property<int>("TrailerForLoadID");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerOrdersID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("TrailerForLoadID")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TrailerOrder.Models.Tractor", b =>
                {
                    b.Property<int>("TractorID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("TractorID");

                    b.ToTable("Tractors");
                });

            modelBuilder.Entity("TrailerOrder.Models.Trailer", b =>
                {
                    b.Property<int>("TrailerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SerialNumber");

                    b.Property<string>("TrailerNumber");

                    b.Property<string>("TrailerStatus");

                    b.HasKey("TrailerID");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TrailerOrder.Models.Employee", b =>
                {
                    b.HasOne("TrailerOrder.Models.Attendance")
                        .WithMany("Employee")
                        .HasForeignKey("AttendanceID");
                });

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.HasOne("TrailerOrder.Models.Customer", "CustomerOrders")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerOrdersID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrailerOrder.Models.Employee", "Driver")
                        .WithMany("Order")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("TrailerOrder.Models.Trailer", "TrailerForLoad")
                        .WithOne("OrderforTrailer")
                        .HasForeignKey("TrailerOrder.Models.Order", "TrailerForLoadID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
