// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TrailerOrder.Data;

namespace TrailerOrder.Migrations
{
    [DbContext(typeof(TrailerOrderDbContext))]
    partial class TrailerOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrailerOrder.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("CustomerName");

                    b.Property<string>("State");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("ZipCode");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TrailerOrder.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LoginStatus");

                    b.Property<int>("OrderID");

                    b.Property<string>("WorkStatus");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<int>("CustomerOrdersID");

                    b.Property<DateTime>("DateAssigned");

                    b.Property<DateTime>("DateDelivered");

                    b.Property<int?>("DriverEmployeeID");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("OrderNumber");

                    b.Property<string>("OrderStatus");

                    b.Property<int>("TrailerForLoadID");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerOrdersID");

                    b.HasIndex("DriverEmployeeID");

                    b.HasIndex("TrailerForLoadID")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TrailerOrder.Models.Trailer", b =>
                {
                    b.Property<int>("TrailerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SerialNumber");

                    b.Property<string>("TrailerNumber");

                    b.Property<string>("TrailerStatus");

                    b.HasKey("TrailerID");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TrailerOrder.Models.Order", b =>
                {
                    b.HasOne("TrailerOrder.Models.Customer", "CustomerOrders")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerOrdersID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrailerOrder.Models.Employee", "Driver")
                        .WithMany("Order")
                        .HasForeignKey("DriverEmployeeID");

                    b.HasOne("TrailerOrder.Models.Trailer", "TrailerForLoad")
                        .WithOne("OrderforTrailer")
                        .HasForeignKey("TrailerOrder.Models.Order", "TrailerForLoadID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
